# Generated by Django 3.1.2 on 2020-10-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swift_realtys', '0002_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='address',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='num_bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='num_bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='text',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
