# Generated by Django 3.1.2 on 2020-10-29 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swift_realtys', '0003_auto_20201028_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='photo',
            field=models.ImageField(default='none', upload_to='homes'),
        ),
    ]
