# Generated by Django 3.1.2 on 2020-10-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swift_realtys', '0004_listing_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
