# Generated by Django 3.2 on 2020-11-01 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('swift_realtys', '0005_listing_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name_plural': 'listings'},
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.ImageField(default='none', upload_to='images'),
        ),
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=200)),
                ('phone_number', models.CharField(default='none', max_length=200)),
                ('email_address', models.EmailField(default='none', max_length=254)),
                ('agency', models.CharField(default='none', max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'realtors',
            },
        ),
    ]
