# Generated by Django 3.2 on 2020-11-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swift_realtys', '0007_alter_listing_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='photo',
            field=models.ImageField(blank=True, upload_to='realtor_photo'),
        ),
    ]
