# Generated by Django 3.1.2 on 2020-10-30 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swift_realtys', '0007_realtor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name_plural': 'listings'},
        ),
        migrations.AlterModelOptions(
            name='realtor',
            options={'verbose_name_plural': 'realtors'},
        ),
    ]
