# Generated by Django 3.1.2 on 2020-11-02 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swift_realtys', '0009_remove_listing_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='favorite',
        ),
    ]
