# Generated by Django 3.2 on 2020-11-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swift_realtys', '0016_auto_20201104_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='favorite',
            field=models.BooleanField(default=True),
        ),
    ]
