# Generated by Django 3.1.3 on 2020-11-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swift_realtys', '0023_alter_listing_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.ImageField(blank=True, default=None, upload_to='images'),
        ),
    ]
