# Generated by Django 3.1.3 on 2020-11-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swift_realtys', '0025_auto_20201105_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='realtor_photo'),
        ),
    ]
