# Generated by Django 3.1.3 on 2020-11-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swift_realtys', '0026_auto_20201105_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='sort_baths',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='sort_beds',
            field=models.BooleanField(default=False),
        ),
    ]
