# Generated by Django 3.1.3 on 2020-11-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swift_realtys', '0027_auto_20201116_0459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_beds', models.BooleanField(default=0)),
                ('sort_baths', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name_plural': 'listings',
            },
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={},
        ),
        migrations.RemoveField(
            model_name='listing',
            name='sort_baths',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='sort_beds',
        ),
    ]
