# Generated by Django 3.1.3 on 2020-11-16 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swift_realtys', '0028_auto_20201116_0505'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sort',
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name_plural': 'listings'},
        ),
    ]
