# Generated by Django 3.1.3 on 2020-11-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swift_realtys', '0030_sort'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sort',
        ),
        migrations.AddField(
            model_name='listing',
            name='sortbybath',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='listing',
            name='sortbybed',
            field=models.BooleanField(default='False'),
        ),
    ]
