# Generated by Django 3.1.3 on 2020-11-23 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swift_realtys', '0031_auto_20201123_0340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='sortbybath',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='sortbybed',
        ),
    ]
